// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardResult: typeof import('./src/components/Card/CardResult.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    FormSearch: typeof import('./src/components/Form/FormSearch.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    Logo: typeof import('./src/components/Logo/Logo.vue')['default']
    ModalSearch: typeof import('./src/components/Modal/ModalSearch.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./src/components/Spinner/Spinner.vue')['default']
  }
}
